### ISSUE TITLE
fractal start --sync does nothing

### ISSUE THREAD

**Issue by trickydisco78** [frctl/fractal#249] opened 2017-05-25 12:25 UTC
I have installed fractal CLI.  I have node 6.10.1 on windows

I run the command start as described in the docs and it does nothing?

![image](https://cloud.githubusercontent.com/assets/3627429/26450095/a293156a-414d-11e7-8b96-bc59eefbdba9.png)

**Comment by colourgarden** [comment] 2017-06-01 14:05
@trickydisco78 Can you confirm you've got the [Fractal CLI tool installed](http://fractal.build/guide/installation#installing-the-fractal-cli-tool)?

**Comment by trickydisco78** [comment] 2017-06-01 14:09
Yep. The only way i can get it to work is to run "yarn run fractal" which then opens the CLI and then i run "start --sync"

**Comment by bux** [comment] 2017-09-19 09:24
Happens for me too

**Comment by colourgarden** [comment] 2017-09-19 10:24
@bux Are you also on Windows? And which Node version?

**Comment by bux** [comment] 2017-09-19 10:41
@colourgarden these are two separate issues.

**Comment by dkhuntrods** [comment] 2017-09-19 11:00
@bux they appear separate but they may have the same root cause. Can you try the new version I've just published, v1.1.7?

**Comment by bux** [comment] 2017-09-19 11:01
I already did and it's working for me. 👍  Though I have to use the git bash cli because (as I've read in another issue) the default cmd cli just tries to open the fractal.js file when running `fractal start --sync`

**Comment by dkhuntrods** [comment] 2017-09-19 11:08
Fantastic!
Did you try renaming the fractal config file, and then setting that in your `package.json`?
```
{
  "fractal": {
    "main": "fractal.config.js"
  }
}
```
It's a slightly easier approach I think.
Also - this will be fixed in v2!

**Comment by bux** [comment] 2017-09-19 11:10
That's exactly what I did in #350
Thanks, though 😄

**Closed** 2017-09-19 13:07 UTC
Labels: v1.x
