### ISSUE TITLE
Option to get non-ugly build log in Jenkins

### ISSUE THREAD

**Issue by julmot** [frctl/fractal#273] opened 2017-07-07 07:22 UTC
It would be nice to have a CI conform build output with a specific option, e.g. `--ci`.

![2017-07-07 09_21_20-](https://user-images.githubusercontent.com/8310677/27947332-b3aebee8-62f5-11e7-98df-a9c8006b05ac.png)

**Comment by tlenex** [comment] 2017-07-07 08:15
Possible duplicate of #226

**Comment by dkhuntrods** [comment] 2017-07-21 11:43
Confirmed duplicate of #226, closing

**Closed by dkhuntrods** 2017-07-21 11:43 UTC
