### ISSUE TITLE
Non-destructive build command

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#54] opened 2016-05-03 14:35 UTC
Currently, running `fractal build` deletes the contents of the target static build folder, before generating new static files. However, in my build folder, I have a shell script to configure a Jenkins deployment. Is there any way (in fractal, at least) to avoid deletion of files like this?

**Comment by sturobson** [comment] 2016-05-03 16:42
something like fractal build --newer or similar - alternatively you could do the build process as part of 'your build tool of choice' task whilst you're compiling / minifying your CSS and JS? @allmarkedup gave a code snippet for this for my yeoman generator task requirement -- works a treat.

**Comment by allmarkedup** [comment] 2016-05-04 08:52
The problem is that if you _don't_ clear out the directory, if you have deleted components in between builds they will still exist in your build directory as the won't get cleaned up. I think as @sturobson says if you want to do any additional steps to get the build directory ready for release then that is probably a good candidate for wrapping up into a separate gulp/grunt/npm scripts task.

Going to close this for now as I don't think that this is something Fractal can/should help with specifically.

**Closed by allmarkedup** 2016-05-04 08:52 UTC
