### ISSUE TITLE
fratal fails to start with 'Microsoft JScript compilation error'

### ISSUE THREAD

**Issue by canoas** [frctl/fractal#56] opened 2016-05-09 11:02 UTC
was just starting this for the first time:
`C:\DEV\2016\style\project-name>fractal start --watch`

and this was the result:

```
Windows Script Host
---------------------------
Script:	C:\DEV\2016\style\project-name\fractal.js
Line:	6
Char:	1
Error:	Syntax error
Code:	800A03EA
Source: 	Microsoft JScript compilation error

```

my version of nodejs is 4.4.2. Any other idea?
thanks

**Comment by johannestroeger** [comment] 2016-05-09 13:10
a colleague of mine is expiring the same. 

`node version: 6.1`
`npm version: 3.8.6`

**Comment by allmarkedup** [comment] 2016-05-10 07:55
Thanks for the report guys. I'm no Windows expert but from a bit of research it sounds like the Fractal is not being run through Node but rather the Windows Script Host interpreter - probably due to the `.js` file extension.

I'm not quite sure why this is the case (or what I can do about it!), but I'll do some more research and let you know if once I've managed to find a solution.

**Comment by DrChills** [comment] 2016-07-04 11:17
+1 

windows 7
node : 4.4.7
npm 3.10.2

**Comment by allmarkedup** [comment] 2016-08-17 11:28
This seems to be working for people now after a small tweak to the bin file so I'm going to go ahead and close this issue. Please re-open if you are still affected when using the latest version.

**Closed by allmarkedup** 2016-08-17 11:28 UTC
Labels: bug

**Comment by jameswragg** [comment] 2016-12-07 13:14
Trying to get this working a colleagues Windows PC they're having this issue too.

I think I know what the issue is, running a `where fractal` from the project root tells me that Windows sees `fractal.js` first and tries to run it through the Windows Script Host interpreter.

```
C:\Projects\madgex-pattern-library> where fractal
C:\Projects\madgex-pattern-library\fractal.js
C:\Users\jim.oneill\AppData\Roaming\npm\fractal
C:\Users\jim.oneill\AppData\Roaming\npm\fractal.cmd
```

Pretty sure that's just how Windows pathing/priority works, so maybe a simple solution is to rename a projects `fractal.js` to `fractal.conf.js` or similar?

node v6.9.1
npm v3.10.8

**Comment by jcrben** [comment] 2017-05-31 19:53
>This seems to be working for people now after a small tweak to the bin file
 @allmarkedup it would have been helpful to point to the tweak you made... trying to figure out an issue in my unrelated topic and any other examples are helpful ;)

**Comment by alexplummer** [comment] 2017-06-28 14:21
Can we get some details of which bin file we are supposed to be editing?..

**Comment by rkrishnaan** [comment] 2017-07-05 15:37
I had the same problem with postman-collection-converter package. The trick is to run the command with .js.cmd at the end. Like this >transform-collection.js.cmd

**Comment by alexplummer** [comment] 2017-07-12 14:19
This issue can be avoided if fractal is run from Git Bash instead of the command prompt.

**Comment by mathurmukul24** [comment] 2017-12-27 07:23
Hi I am still getting error while running cucumber --version on cmd as well as gitbash

Node - v8.9.3
npm - v5.5.1

Script : C:\Users\AppData\Roaming\npm\cucumber.js
Line: 1
Char: 1
Error: Invalid Character
Code: 800A03F6
Source: Microsoft Jscript compilation error

**Comment by aunitz** [comment] 2017-12-27 07:23
El mensaje ha llegado correctamente pero... estoy de vacaciones hasta el próximo 8 de enero. Atenderé tu correo a la vuelta. 

Si por el motivo que fuere necesitas ponerte en contacto con Adimedia puedes hacerlo en info@adimedia.net o en el Telf. 943 63 57 37.

**Comment by mathurmukul24** [comment] 2017-12-27 07:25
gracias esperaremos por su correo

**Comment by joshas** [comment] 2019-03-24 13:05
Using Git Bash gives same error.
Best workaround on Windows is to rename fractal.js file and add config to package.json to use new config file: https://github.com/frctl/fractal/issues/118#issuecomment-255254117

**Comment by paul-hanneforth** [comment] 2020-10-22 15:10
I had the same problem but with another npm package. The solution was to go to "C:\Program Files\nodejs", then find the bat file for the package. In my case the package was named "powerline" so the bat file was named "powerline.bat". Then you need to open it and add "node" before line 4

**Comment by fairking** [comment] 2021-12-13 10:06
https://github.com/ficonsulting/RInno/issues/44#issuecomment-992299431
