### ISSUE TITLE
Maximum call stack size exceeded when trying to install

### ISSUE THREAD

**Issue by ethikz** [frctl/fractal#487] opened 2019-02-25 21:56 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

When running `npm i` after node gets to creating the symlinks, it eventually fails with this error:

```
npm verb stack RangeError: Maximum call stack size exceeded
npm verb stack     at RegExp.test (<anonymous>)
npm verb stack     at isDepOptional (/usr/local/lib/node_modules/npm/lib/install/deps.js:405:45)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:414:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
npm verb stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
```

Webpack had this issue previously but it's been fixed.

I am using `"@frctl/fractal": "1.1.7", "@frctl/handlebars": "1.1.4", "@frctl/mandelbrot": "1.2.0"`.  I have them in the *dependencies* section and even tried the *devDependencies* section and still causes the same issue.  If I remove all 3 of the packages then the creation of symlinks works fine.  If I add any of those packages it will fail.

This only happens using **npm** oddly enough but I suspect is has something to do with the difference between how yarn and npm reference packages/symlinks?

### Steps to Reproduce

1. `npm i @frctl/fractal`
2. `npm i @frctl/handlebars`
3. `npm i @frctl/mandelbrot`

**Expected behavior:** [What you expect to happen]
To install without issues

**Actual behavior:** [What actually happens]
**1**. This is the error I get
```
npm ERR! path /Development/project/node_modules/highlight.js/tools/build.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Development/project/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**2**. This is the error I get `npm ERR! Maximum call stack size exceeded`, reference above stack
**3**. This is the error I get `npm ERR! Maximum call stack size exceeded`, reference above stack

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Reduced test case:** (if relevant) - this might be a link to a gist of your `fractal.js` file, or a git repo for more complex issues

### Versions

* No version because it doesn't install
* Node v11.10.0

This just started happening today.  Everything installed fine last week.

**Comment by ethikz** [comment] 2019-02-25 22:00
As a quick update, I did find this which seems to be the issue.

https://github.com/highlightjs/highlight.js/issues/1984

**Comment by LeBenLeBen** [comment] 2019-02-26 06:57
Yes, this issue was indeed caused by Highlight.js. It should be fixed now on their side, can you please try again and reopen if you still encouter issues?

**Closed by LeBenLeBen** 2019-02-26 06:57 UTC

**Comment by ethikz** [comment] 2019-02-26 10:55
@LeBenLeBen confirmed, it now works.  Thanks for following up on this!
