### ISSUE TITLE
Fractal dev process (fractal start --sync) exits on 404

### ISSUE THREAD

**Issue by skoldborg** [frctl/fractal#531] opened 2019-11-12 13:24 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Fractal Documentation for information about your issue: https://fractal.build/guide
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Afrctl

### Description

Fractal dev server exits on 404.

### Steps to Reproduce

1. Run `fractal start --sync`
2. Point browser to a component that doesn't exist

**Expected behavior:** 

In earlier versions (<=1.1.4) console returns warning about 404 but fractal process kept running.

**Actual behavior:** 

Console returns warning about 404 and fractal process exits.

### Versions

* I've tried @frctl/fractal 1.1.6 and 1.2.0
* What version of Node.js are you running? 10.15.1

**Comment by Chapabu** [comment] 2019-11-12 23:53
Thanks for reporting. This is a dupe of #514 and was fixed in #515. If you update to `@next` (or `1.2.1-beta.1`) this has been fixed. There's no current timeline for a full release, but it won't be that far away - couple of weeks at most.

**Closed by Chapabu** 2019-11-12 23:53 UTC
