### ISSUE TITLE
`default.context` not available in (twig) preview templates

### ISSUE THREAD

**Issue by therealpecus** [frctl/fractal#1042] opened 2021-05-25 10:34 UTC
`global.context` data is not made available to (twig) preview templates.

This used to work with version 1.1.x of fractal.

### Steps to reproduce the issue

1. set a global context 
```
fractal.components.set('default.context', {
	manifest: {
		'main.js': 'main.h65dd5.js',
	}
})
```
2. use the context in a preview template
```
{{ dump(manifest['main.js']) }}
```
3. output is `undefined`. It should be `main.h65dd5.js`.

**Reproduces how often:**

100%

### Reduced test case

https://gist.github.com/therealpecus/a9ba99ddff7b0ebecf1cd39871c3e68d

### Context

-   Fractal version: @frctl/fractal@1.5.8
-   Twig adapter: @frctl/twig@1.2.9
-   Node version: v14.16.1
-   OS: Mac OS 10.15.7

**Comment by therealpecus** [comment] 2021-05-25 10:45
I found a workaround, but the issue remains:

using `_config.components.default.context.manifest['main.js']` works.

**Comment by mihkeleidast** [comment] 2021-05-25 16:14
Thanks for the issue! Weird stuff. I took a project of mine, updated the Fractal dependencies to latest and your example works like a charm. In this repo, however, it did not. Looked around a bit - this seems to be dependent on the file structure. If you put the preview template directly in the components directory, it acts as the default preview for all components and it totally disregards what you've set as the default preview in the config. However, if you move the preview template to a subdirectory, it works.

![image](https://user-images.githubusercontent.com/1892091/119532286-6b1c7e80-bd8d-11eb-854a-142d394d5f5d.png)

**Comment by mihkeleidast** [comment] 2021-05-25 16:27
Are you sure it worked differently in an earlier version? Could you provide a repository with older versions to demonstrate that?

**Comment by therealpecus** [comment] 2021-05-25 20:54
> Are you sure it worked differently in an earlier version? Could you provide a repository with older versions to demonstrate that?

I double checked and I was mistaken: it never worked.

Thanks for reviewing the issue so quickly! The preview template position in the directory structure seems to be the culprit, and it might be enough to update the documentation to mention it. Currently, the docs say:

> Preview layouts are just another component, and so must reside in your component directory. Like any other components, preview layouts can be hidden by prefixing their name with an underscore if you don't want them to show up in listings or navigation.
>
> For example, we could create a preview layout called `_preview.hbs` in the root our components directory: 

[source](https://fractal.build/guide/components/preview-layouts.html#creating-a-preview-layout)

The other place where it might be useful to add a note is [when documenting `default.context`](https://fractal.build/guide/components/configuration-reference.html#default-context):
> default.context
>
> Global context data that will be made available to all components when rendering previews, unless overridden in a collection or component configuration file.

**Comment by mihkeleidast** [comment] 2021-05-26 06:06
I'd still categorize this as a bug / unexpected behavior, it's just that since it's not a regression and has worked this way since 2016, it gets a little bit lower priority.

**Comment by Art4** [comment] 2021-07-02 12:28
I've got the same problem.

**Comment by mihkeleidast** [comment] 2021-07-02 13:29
Help out with testing / reviewing the fix in the PR linked above! If noone tells us it's better with the fix, it'll never get merged/released.

Or, if the fix does not solve the issues, more info is needed to investigate further.

**Comment by therealpecus** [comment] 2021-07-02 13:30
> Help out with testing / reviewing the fix in the PR linked above! If noone tells us it's better with the fix, it'll never get merged/released.
> 
> Or, if the fix does not solve the issues, more info is needed to investigate further.

I had missed it! I'll review the PR

**Comment by therealpecus** [comment] 2021-07-06 09:12
@mihkeleidast  I reviewed the PR by testing the same case that prompted this bug and I can confirm it is fixed. I do not have write permissions on the repo but LGTM and should be merged

**Closed** 2021-07-06 14:23 UTC
Labels: bug
