### ISSUE TITLE
Feature request: Built-in placeholder image generation

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/fractal#9] opened 2016-03-05 17:49 UTC
Rather than link out to a (remote) placeholder image service, instead provide one that can be used locally (and offline).

**Comment by allmarkedup** [comment] 2016-03-05 21:20
This is definitely a good idea but is really plugin territory I think. You currently can't inject regular express middleware into the web plugin but if I opened that up then you could use an existing local placeholder generator lib (I'm sure there are some!) instead of re-inventing the wheel.

Actually I really like this idea - it would open up a _lot_ of additional possibilities. I'll get on it!

**Comment by paulrobertlloyd** [comment] 2016-03-05 21:46
I remember using [img-placeholder](https://www.npmjs.com/package/img-placeholder) (or was it [node-img-placeholder](https://www.npmjs.com/package/node-img-placeholder)) on a project last year… can’t remember how successfully. But yes, very useful when creating placeholder content for components.

**Comment by allmarkedup** [comment] 2016-03-05 21:55
I'm just tinkering with this now and it's pretty straightforward to get it up and running when using the development server. However the problem is that the static build of the site will reference the image URLs but they wouldn't exist if the server isn't running. So not useful if you want to give a static export to a client.

I'll still add in the middleware option but I'll try and think if there is anyway else that this could be done that is more compatible with the static export.

**Comment by paulrobertlloyd** [comment] 2016-03-05 21:56
Ah, of course. Can you note write the placeholder images to the static folder?

**Comment by allmarkedup** [comment] 2016-03-05 22:00
Yeah possibly... but it might get complicated as the placeholder image generation is typically on-demand and so any that hadn't been requested wouldn't be in the static folder. A library that generated placeholders as data URIs in the config file would work, but would make the code view pretty verbose!

**Comment by allmarkedup** [comment] 2016-03-05 22:20
Ok this is actually way nastier that I thought. All the node placeholder image services need Cairo which has to be installed seperately via brew. WIll close this for now as with the middleware support (which I've just added) users can hack this in themselves if they think it's worth the effort!

**Closed by allmarkedup** 2016-03-05 22:20 UTC
Labels: feature request

**Comment by paulrobertlloyd** [comment] 2016-03-05 22:23
[![Cairo!](http://img.youtube.com/vi/iQDldgNPGFo/0.jpg)](http://www.youtube.com/watch?v=iQDldgNPGFo)
