### ISSUE TITLE
1.2.1 Markdown Code Fail

### ISSUE THREAD

**Issue by dutscher** [frctl/fractal#557] opened 2020-03-23 14:20 UTC
Hi There,

we are currently on 1.1.7 and saw that there was an release 1.2.1
what i found is a bug in the markdown.js file:

https://github.com/frctl/fractal/compare/v1.1.7...v1.2.1#diff-6babe5ef701ed6699152e572b17e31c9

in 1.1.7 it was:
```<code><pre>${code}</pre></code>```
in 1.2.1 it is:
```<pre><code>${code}</code></pre>```

and this will do simple markdown code ` ```<html ...>``` ` to single line code.

1.1.7 markdown
![image](https://user-images.githubusercontent.com/14682/77325543-cd589a00-6d18-11ea-8019-79c734d2c3ee.png)
looks now with 1.2.1 same correct markdown:
![image](https://user-images.githubusercontent.com/14682/77325625-eb25ff00-6d18-11ea-9a1f-157c853b1e17.png)

cheers

**Comment by risker** [comment] 2020-03-23 17:50
This is a duplicate of #532, which was fixed by frctl/mandelbrot#79

**Closed by risker** 2020-03-23 17:50 UTC
Labels: bug, duplicate
