### ISSUE TITLE
Markdown issues

### ISSUE THREAD

**Issue by proko** [frctl/fractal#101] opened 2016-07-26 18:21 UTC
First many thanks for what you've made here!  It's really the first styleguide tool that made sense from the beginning.

Looks like there are some problems with Markdown in Documents.
Blockquotes are just ignored
```
> This will give normal text
```
and inline code inside a code block is kind of broken
```
`test`
```
gives 
```
%60test%60
```

**Comment by allmarkedup** [comment] 2016-07-26 19:44
Hi @proko - really glad that you are finding it useful. I've just checked and you are correct, blockquotes do not currently have any styling associated with them (although they are actually being converted correctly!). I'll update the theme to add some styling for them in the next release.

With the code block issue - I'm not seeing that behaviour myself. Have you changed any of markdown configuration settings? And are you using the default documentation template engine?

**Comment by allmarkedup** [comment] 2016-07-26 19:55
Ahh actually I've just reproduced it - it didn't realise at first you meant when using the single backticks inside a fenced code block. Yes that looks like a bug... I'll dig into it as soon as I can! Thanks :-)

**Comment by allmarkedup** [comment] 2016-07-26 20:40
@proko - I've just released v1.0.4 that should fix the code block issue. If you update and it's still a problem please feel let me know.

I'm tracking the blockquote issue over on the Mandelbrot theme repo (https://github.com/frctl/mandelbrot/issues/30) so will close this one down.

**Closed by allmarkedup** 2016-07-26 20:40 UTC
Labels: bug
